CREATE TABLE users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL
);

CREATE TABLE records (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  period TEXT NOT NULL,
  revenue REAL DEFAULT 0,
  cogs REAL DEFAULT 0,
  expenses REAL DEFAULT 0,
  taxes REAL DEFAULT 0,
  currency TEXT DEFAULT 'UZS',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
